services:
  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app-network

  gateway1:
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    container_name: express-gateway-1
    ports:
      - "8081:8083"
    environment:
      - REDIS_URL=redis://redis:6379
      - INSTANCE_NAME=gateway-1
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network

  gateway2:
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    container_name: express-gateway-2
    ports:
      - "8082:8083"
    environment:
      - REDIS_URL=redis://redis:6379
      - INSTANCE_NAME=gateway-2
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network

  gateway3:
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    container_name: express-gateway-3
    ports:
      - "8083:8083"
    environment:
      - REDIS_URL=redis://redis:6379
      - INSTANCE_NAME=gateway-3
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network

  haproxy:
    build:
      context: src/haproxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - gateway1
      - gateway2
      - gateway3
    networks:
      - app-network
networks:
  app-network:
    driver: bridge