version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: src/gateway/Dockerfile
    container_name: express-gateway
    ports:
      - "8083:8083"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped