global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']   #check here too if it fails again

  - job_name: 'ticket-service-1'
    static_configs:
      - targets: ['ticket-service-1:8082']

  - job_name: 'ticket-service-2'
    static_configs:
      - targets: ['ticket-service-2:8083']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8084']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8088']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
