server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

# scrape_configs:
#   - job_name: services
#     static_configs:
#       - targets: ['localhost']
#         labels:
#           job: services
#           __path__: /app/*/logs/*.log
#     relabel_configs:
#       - source_labels: [__path__]
#         regex: /app/([^/]+)/logs/.*\.log
#         target_label: service
#         replacement: $1
#     pipeline_stages:
#       - json:
#           expressions:
#             level: level
#             msg: message

scrape_configs:
  - job_name: auth-service
    static_configs:
      - targets: ['localhost']
        labels:
          job: auth-service
          service: auth
          __path__: /app/auth/logs/service.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: message

  - job_name: event-service
    static_configs:
      - targets: ['localhost']
        labels:
          job: event-service
          service: event
          __path__: /app/event-service/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: message

  - job_name: payment-service
    static_configs:
      - targets: ['localhost']
        labels:
          job: payment-service
          service: payment
          __path__: /app/payment/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: message

  - job_name: reservation-service
    static_configs:
      - targets: ['localhost']
        labels:
          job: reservation-service
          service: reservation
          __path__: /app/reservation-service/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: message

  - job_name: ticket-service
    static_configs:
      - targets: ['localhost']
        labels:
          job: ticket-service
          service: ticket
          __path__: /app/ticket-service/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: message

  - job_name: user-service
    static_configs:
      - targets: ['localhost']
        labels:
          job: user-service
          service: user
          __path__: /app/user-service/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: message
