# server:
#   http_listen_port: 9080
#   grpc_listen_port: 0

# positions:
#   filename: /tmp/positions.yaml

# clients:
#   - url: http://loki:3100/loki/api/v1/push

# scrape_configs:
#   - job_name: system
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: varlogs
#           __path__: /var/log/*log

#   - job_name: docker
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: docker
#           __path__: /var/lib/docker/containers/*/*.log



# ???????????????????????????????????????????????????????????????????????????????????????????????????????????????


# server:
#   http_listen_port: 9080
#   grpc_listen_port: 0

# positions:
#   filename: /tmp/positions.yaml

# clients:
#   - url: http://loki:3100/loki/api/v1/push

# scrape_configs:
#   - job_name: docker
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: docker
#           __path__: /var/lib/docker/containers/*/*.log
#     pipeline_stages:
#       - docker: {}

#   - job_name: auth-service
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: auth-service
#           service: auth
#           __path__: /var/log/auth-service/*.log
#     pipeline_stages:
#       - json: {}
#     read_from: beginning

#   - job_name: cms-service
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: cms-service
#           service: cms
#           __path__: /var/log/cms-service/*.log
#     pipeline_stages:
#       - json: {}
#     read_from: beginning

#   - job_name: notification-service
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: notification-service
#           service: notification
#           __path__: /var/log/notification-service/*.log
#     pipeline_stages:
#       - json: {}
#     read_from: beginning

#   - job_name: profile-service
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: profile-service
#           service: profile
#           __path__: /var/log/profile-service/*.log
#     pipeline_stages:
#       - json: {}
#     read_from: beginning

#   - job_name: review-service
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: review-service
#           service: review
#           __path__: /var/log/review-service/*.log
#     pipeline_stages:
#       - json: {}
#     read_from: beginning

#   - job_name: streaming-service
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: streaming-service
#           service: streaming
#           __path__: /var/log/streaming-service/*.log
#     pipeline_stages:
#       - json: {}
#     read_from: beginning


# =============================================================================================================


# server:
#   http_listen_port: 9080
#   grpc_listen_port: 0

# positions:
#   filename: /tmp/positions.yaml

# clients:
#   - url: http://loki:3100/loki/api/v1/push

# pipeline_stages:
#   - json:
#       expressions: {}


# scrape_configs:
#   - job_name: auth-service
#     static_configs:
#       - targets: ['localhost']
#         labels:
#           job: auth
#           service: auth
#           __path__: /software-arch/src/services/auth/logs/*.log
#     pipeline_stages:
#       - json: {}
#     # read_from: beginning

#   - job_name: event-service
#     static_configs:
#       - targets: ['localhost']
#         labels:
#           job: event
#           service: event
#           __path__: /software-arch/src/services/event-service/logs/*.log
#     pipeline_stages:
#       - json: {}
#     # read_from: beginning

#   - job_name: payment-service
#     static_configs:
#       - targets: ['localhost']
#         labels:
#           job: payment
#           service: payment
#           __path__: /software-arch/src/services/payment/logs/*.log
#     pipeline_stages:
#       - json: {}
#     # read_from: beginning

#   - job_name: reservation-service
#     static_configs:
#       - targets: ['localhost']
#         labels:
#           job: reservation
#           service: reservation
#           __path__: /software-arch/src/services/reservation-service/logs/*.log
#     pipeline_stages:
#       - json: {}
#     # read_from: beginning

#   - job_name: ticker-service
#     static_configs:
#       - targets: ['localhost']
#         labels:
#           job: ticker
#           service: ticker
#           __path__: /software-arch/src/services/ticker-service/logs/*.log
#     pipeline_stages:
#       - json: {}
#     # read_from: beginning

#   - job_name: user-service
#     static_configs:
#       - targets: ['localhost']
#         labels:
#           job: user
#           service: user
#           __path__: /software-arch/src/services/user-service/logs/*.log
#     pipeline_stages:
#       - json: {}
#     # read_from: beginning

# server:
#   http_listen_port: 9080
#   grpc_listen_port: 0

# positions:
#   filename: /tmp/positions.yaml

# clients:
#   - url: http://loki:3100/loki/api/v1/push

# scrape_configs:
#   - job_name: auth-service
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: auth-service
#           service: auth
#           __path__: /software-arch/src/services/auth/logs/*.log
#     pipeline_stages:
#       - json:
#           expressions: {}
#     read_from: beginning

#   - job_name: event-service
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: event-service
#           service: event
#           __path__: /software-arch/src/services/event-service/logs/*.log
#     pipeline_stages:
#       - json:
#           expressions: {}
#     read_from: beginning

#   - job_name: payment-service
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: payment-service
#           service: payment
#           __path__: /software-arch/src/services/payment/logs/*.log
#     pipeline_stages:
#       - json:
#           expressions: {}
#     read_from: beginning

#   - job_name: reservation-service
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: reservation-service
#           service: reservation
#           __path__: /software-arch/src/services/reservation-service/logs/*.log
#     pipeline_stages:
#       - json:
#           expressions: {}
#     read_from: beginning

#   - job_name: ticket-service
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: ticket-service
#           service: ticket
#           __path__: /software-arch/src/services/ticket-service/logs/*.log
#     pipeline_stages:
#       - json:
#           expressions: {}
#     read_from: beginning

#   - job_name: user-service
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: user-service
#           service: user
#           __path__: /software-arch/src/services/user-service/logs/*.log
#     pipeline_stages:
#       - json:
#           expressions: {}
#     read_from: beginning


# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: auth-service
    static_configs:
      - targets: ['localhost']
        labels:
          job: auth-service
          service: auth
          __path__: /software-arch/src/services/auth/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: message

  - job_name: event-service
    static_configs:
      - targets: ['localhost']
        labels:
          job: event-service
          service: event
          __path__: /software-arch/src/services/event-service/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: message

  - job_name: payment-service
    static_configs:
      - targets: ['localhost']
        labels:
          job: payment-service
          service: payment
          __path__: /software-arch/src/services/payment/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: message

  - job_name: reservation-service
    static_configs:
      - targets: ['localhost']
        labels:
          job: reservation-service
          service: reservation
          __path__: /software-arch/src/services/reservation-service/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: message

  - job_name: ticket-service
    static_configs:
      - targets: ['localhost']
        labels:
          job: ticket-service
          service: ticket
          __path__: /software-arch/src/services/ticket-service/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: message

  - job_name: user-service
    static_configs:
      - targets: ['localhost']
        labels:
          job: user-service
          service: user
          __path__: /software-arch/src/services/user-service/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: message
