version: '3'
services:
  ticket-service:
    build: ./ticket-service
    ports:
      - "8082:8082"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket_db
    ports:
      - "5432:5432"
